### ISSUE TITLE
Ability to delete urls

### ISSUE THREAD

**Issue by rithvikvibhu** [neocotic/yourls-api#16]
Quite surprised to see there isn't any delete method. Could you please add it or give me a basic idea on how I could go about this? Thanks

**Comment by airmrcr** [comment]
This library is really just a wrapper around the [official YOURLS API](https://yourls.org/#API) which is read only for some reason.

If you'd like to see delete functionality, you probably want to open a feature request issue on [their repository](https://github.com/YOURLS/YOURLS) or, better yet, a pull request that implements it.

If delete functionally is added to the live API, I will be able to add it here.

**Comment by rithvikvibhu** [comment]
@neocotic Huh. That's weird. I found a plugin on their [Plugins List](https://github.com/YOURLS/YOURLS/wiki/Plugin-List).
https://github.com/claytondaley/yourls-api-delete adds a `delete` action to the standard API.

I know that this library is a wrapper for the official API only, but considering that this is a basic necessary feature, I hope you will agree to supporting this.

**Comment by airmrcr** [comment]
I am reluctant to support individual unofficial YOURLS plugins as part of this library, however, the code is fully open source so you are free to fork and extend it. Alternatively, you could create a plugin for this library itself (see #9).

**Comment by rithvikvibhu** [comment]
I think I'll go the custom API route, doesn't seem difficult. I'll let you know how it goes. Thanks!

**Comment by rithvikvibhu** [comment]
For others' reference, I got it working with this:

1. Install the [yourls-api-delete](https://github.com/claytondaley/yourls-api-delete) plugin and enable it on the plugins page.
2. Insert this somewhere in your script:
```js
yourls.deleteUrl = function(url, callback) {
  var data = {
    action: 'delete',
    shorturl: url
  };
  this.sendRequest(data, ['statusCode', 'simple', 'message'], callback);
  return this;
};
```
3. Use it this way:
```js
yourls.deleteUrl(url, (result, response) => {
  console.log(result, response);
  if (result.statusCode == 200) {
    alert('Deleted url.');
  } else {
    alert('Error deleting. Check console.');
  }
});
```
It would be neater to hack the URL instead of yourls itself, but hey, who reads the code right?
